version: '3.7'

services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/backend
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=libraries_user
      - POSTGRES_PASSWORD=change_me
      - POSTGRES_DB=libraries_user
volumes:
  postgres_data:
